env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
  - prettier/prettier
# plugins:
#   - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  {
    no-console: 0,
    import/extensions: 0,
    import/named: off,
    comma-dangle: [2, always-multiline],
    import/no-name-as-default: 0,
    import/no-name-as-default-member: 0,
  }
