env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
  - prettier/prettier
# plugins:
#   - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  {
    no-console: 0,
    import/extensions: 0,
    import/named: off,
    import/no-named-as-default: off,
    import/no-named-as-default-member: off,
  }
